//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Examen
    {
        public Examen()
        {
            this.Titulo = "Título del Examen";
            this.TiempoMaximo = new TimeSpan(0, 30, 0);
            this.PuntajeMaximo = 20;
            this.FechaEjecucion = DateTime.Now;
            this.Pregunta = new HashSet<Pregunta>();
        }
    
        public int Id { get; set; }
        [Required]
        public string Titulo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaEjecucion { get; set; }
        public System.TimeSpan TiempoMaximo { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> PuntajeMaximo { get; set; }
        [Required]
        public Nullable<int> IdLinea { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Pregunta> Pregunta { get; set; }
        public virtual Linea Linea { get; set; }
    }
}
