//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamenUsuario
    {
        public ExamenUsuario()
        {
            this.PreguntaUsuario = new HashSet<PreguntaUsuario>();
            this.RespuestaUsuario = new HashSet<RespuestaUsuario>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdExamen { get; set; }
        public Nullable<decimal> Puntaje { get; set; }
        public Nullable<System.TimeSpan> Tiempo { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<int> IdEjecutivo { get; set; }
        public Nullable<int> IdAster { get; set; }
        public Nullable<int> IdPreguntaActual { get; set; }
    
        public virtual Examen Examen { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual UserProfile UserProfile2 { get; set; }
        public virtual ICollection<PreguntaUsuario> PreguntaUsuario { get; set; }
        public virtual ICollection<RespuestaUsuario> RespuestaUsuario { get; set; }
    }
}
