//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.ExamenUsuario = new HashSet<ExamenUsuario>();
            this.PreguntaUsuario = new HashSet<PreguntaUsuario>();
            this.RespuestaUsuario = new HashSet<RespuestaUsuario>();
        }
    
        [Key]
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UrlImagen { get; set; }
    
        public virtual ICollection<ExamenUsuario> ExamenUsuario { get; set; }
        public virtual ICollection<PreguntaUsuario> PreguntaUsuario { get; set; }
        public virtual ICollection<RespuestaUsuario> RespuestaUsuario { get; set; }
    }
}
