//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.ExamenUsuario = new HashSet<ExamenUsuario>();
            this.PreguntaUsuario = new HashSet<PreguntaUsuario>();
            this.RespuestaUsuario = new HashSet<RespuestaUsuario>();
        }
    
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string NombreUsuario { get; set; }
        public string Contraseña { get; set; }
    
        public virtual ICollection<ExamenUsuario> ExamenUsuario { get; set; }
        public virtual ICollection<PreguntaUsuario> PreguntaUsuario { get; set; }
        public virtual ICollection<RespuestaUsuario> RespuestaUsuario { get; set; }
    }
}
