//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsApp.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class webpages_Roles
    {
        [Display(Name="Id")]
        public int RoleId { get; set; }
        [Display(Name = "Nombre de Rol")]
        public string RoleName { get; set; }
    }
}
