//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Examen
    {
        public Examen()
        {
            this.Pregunta = new HashSet<Pregunta>();
        }
    
        public int IdExamen { get; set; }
        [Required]
        [DisplayName("Nombre de Examen")]
        public string NombreExamen { get; set; }
        [Required]
        public string TítuloExamen { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaEjecucion { get; set; }
        public System.TimeSpan TiempoMaximo { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Pregunta> Pregunta { get; set; }
    }
}
