//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int IdRespuesta { get; set; }
        public string TextoRespuesta { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public Nullable<int> EsCorrecta { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
    }
}
