// <auto-generated />
namespace TestsApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TestsAppBD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestsAppBD));
        
        string IMigrationMetadata.Id
        {
            get { return "201303072030057_TestsAppBD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
